### ISSUE TITLE
New Tutorial Request - [Dynamic Memory Allocation] in C tutorial.

### ISSUE THREAD

**Issue by Ayu1C** [onecompiler/tutorials#29]
Hey @onecompiler-ops !

I saw that there is no tutorial for **"Dynamic Memory Allocation"** in C tutorial folder.

I want to add this topic's tutorial .
Kindly assign this issue to me and add the label  "**Hacktoberfest**" to this issue.

**Comment by Ayu1C** [comment]
@onecompiler-ops 
Please accept the pull request #32 for this issue.

**Comment by onecompiler-ops** [comment]
Plagiarized content detected. You have been blocked from this community.
